# Generated by Django 5.1.6 on 2025-03-04 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),  # Use your earliest migration that doesn't involve themes or motions
    ]

    operations = [
        # Create Theme model
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        # Create Motion model
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition_type', models.CharField(choices=[('General', 'General'), ('WUDC', 'World Universities Debating Championship'), ('PDA', 'Public Display of Abby'), ('AIDA', 'Asian Intervarsity Debating Association'), ('ABP', 'Asian British Parliamentary')], default='General', max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='api.theme')),
            ],
            options={
                'db_table': 'api_motion',
            },
        ),
    ]
