# Generated by Django 5.1.6 on 2025-03-05 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recreate_theme_and_motion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='round',
            name='started',
        ),
        migrations.AddField(
            model_name='round',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='round',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('ALLOCATION', 'Allocation'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='SETUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='format',
            field=models.CharField(choices=[('ABP', 'British Parliamentary'), ('PDA', 'Asian Parliamentary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motion'),
        ),
        migrations.CreateModel(
            name='RoundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Prime Minister', 'Prime Minister'), ('Deputy Prime Minister', 'Deputy Prime Minister'), ('Member of Government', 'Member of Government'), ('Government Whip', 'Government Whip'), ('Leader of Opposition', 'Leader of Opposition'), ('Deputy Leader of Opposition', 'Deputy Leader of Opposition'), ('Member of Opposition', 'Member of Opposition'), ('Opposition Whip', 'Opposition Whip'), ('Chair Adjudicator', 'Chair Adjudicator'), ('Panelist', 'Panelist'), ('Trainee', 'Trainee'), ('Spectator', 'Spectator')], max_length=30)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('round', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
