# Generated by Django 5.1.6 on 2025-03-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_manual_add_round_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakerscore',
            name='round',
        ),
        migrations.RemoveField(
            model_name='speakerscore',
            name='speaker',
        ),
        migrations.AddField(
            model_name='speakerscore',
            name='allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roundallocation'),
        ),
        migrations.AddField(
            model_name='speakerscore',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('ALLOCATION', 'Allocation'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='SETUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motion'),
        ),
        migrations.AlterField(
            model_name='speakerscore',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ROUND_START', 'Round Starting'), ('ROUND_END', 'Round Ended'), ('ROLE_ASSIGNED', 'Role Assigned'), ('RESULTS_AVAILABLE', 'Results Available'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_side', models.CharField(choices=[('GOVERNMENT', 'Government'), ('OPPOSITION', 'Opposition')], max_length=20)),
                ('summary', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.round')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='speakerscore',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_scores', to='api.roundresult'),
        ),
        migrations.AddConstraint(
            model_name='speakerscore',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation__isnull', False), ('result__isnull', False)), fields=('result', 'allocation'), name='unique_result_allocation'),
        ),
    ]
