# Generated by Django 5.1.6 on 2025-03-07 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_speakerscore_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.motion'),
        ),
    ]
